name: Build FastGPT images in Personal warehouse
on:
  workflow_dispatch:
  push:
    paths:
      - "projects/app/**"
      - "packages/**"
    branches:
      - "main"
jobs:
  build-fastgpt-images:
    runs-on: ubuntu-20.04
    if: github.repository != 'labring/FastGPT'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            mxdlzg/FastGPT
            ghcr.io/${{ github.repository }}

      - name: Build and push image for main branch or tag push event
        uses: docker/build-push-action@v3
        with:
          context: .
          file: projects/app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: name=app
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository_owner }}/FastGPT
            org.opencontainers.image.description=fastgpt image
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
